name: fintech-innovation

channels:
  - conda-forge

dependencies:
  - pandas
  - pytorch
  - numpy
  - pip
  - tqdm
  
  - pip:
    - sec-edgar-downloader
    - bs4
    - lxml
    - transformers
    - dotenv
    - streamlit